### ISSUE TITLE
README: add a GIF/video to show use cases.

### ISSUE THREAD

**Issue by elong0527** [Merck/boxly#14]
Please include a GIF/video in the README file to illustrate the package.

**Comment by elong0527** [comment]
Cool, how about we transfer it to GIF and directly embed the file into source code.

So it save one click from user and package is self contain.

https://ezgif.com/video-to-gif

**Comment by nanxstats** [comment]
I _think_ the MP4 approach is a superior solution for animated recordings in 2023, considering GIF is really a format with so many limitations that did not age well.
