### ISSUE TITLE
Repo description

### ISSUE THREAD

**Issue by nanxstats** [Merck/boxly#21]
I think this description would be a bit better:

> Create interactive box plots with ease, ideal for visualizing data from lab tests, vital signs, electrocardiograms, and more.

compared to the current

> Create interactive box plot for lab test, vital signs, electrocardiogram etc.

The reasoning:

1. Not limiting to visualizing only the listed types of data.
1. Consistent usage of plurals.
1. Avoids using "etc."

**Comment by elong0527** [comment]
The description has been updated in previous PR. Would you want to create another PR based on your suggestions?

**Comment by nanxstats** [comment]
This description:

<img width="592" alt="Screenshot 2023-06-01 at 9 10 07 PM" src="https://github.com/Merck/boxly/assets/199363/be916da8-5dc5-4fff-9157-80d27f7e3b43">

**Comment by wangben718** [comment]
Change to 'Interactive box plot for clinical trial analysis.'

**Comment by nanxstats** [comment]
@wangben718 Please remove the ending period to be consistent with all other repos.
