### ISSUE TITLE
Release boxly 0.1.0

### ISSUE THREAD

**Issue by elong0527** [Merck/boxly#24]
Prepare for release

- [x] Check current CRAN check results
- [x] Check licensing of included files
- [x] Review pkgdown reference index for, e.g., missing topics
- [x] Bump version
- [x] Update `cran-comments.md` (optional)
- [x] Update NEWS.md
- [x] Review pkgdown website
- [x] `urlchecker::url_check()`
- [x] Check with local machine
- [x] Check with GitHub Actions
- [x] Check with win-builder

Submit to CRAN

- [x] Draft GitHub release
- [x] Submit to CRAN via web form
- [x] Approve emails

Wait for CRAN

- [x] Accepted :tada:
- [ ] Post on r-packages mailing list
- [ ] Tweet

**Comment by nanxstats** [comment]
I'm not comfortable with a CRAN release until https://github.com/Merck/boxly/issues/25 and https://github.com/Merck/boxly/issues/26 are resolved.

**Comment by nanxstats** [comment]
Also, you are missing the "First release" section:

First release

- [ ] Proof read `Title:` and `Description:` and ensure they are informative
- [ ] Check that all exported functions have `@returns` and `@examples`
- [ ] Check that `Authors@R:` includes a copyright holder (role 'cph')
- [ ] Review [extrachecks](https://github.com/DavisVaughan/extrachecks)
- [ ] `usethis::use_cran_comments()` (optional)

**Comment by nanxstats** [comment]
On CRAN 2023-06-14.
