### ISSUE TITLE
output shown not well on the knitted output when multiple box plot 

### ISSUE THREAD

**Issue by wangben718** [Merck/boxly#27]
When trying multiple box plots in one RMD file, the output display blank.
![image](https://github.com/Merck/boxly/assets/85646030/c4ed63ff-2696-482d-9c4a-5cf22d59682e)

**Comment by wangben718** [comment]
HTML output works abnormal if we have multiple object generated by `crosstalk` and `plotly` together on one Rmarkdown file.
See this simple example:
---
title: "Untitled"
output: html_document
---

```{r }
library(tidyverse)
library(crosstalk)
library(plotly)
library(DT)
diamonds <- crosstalk::SharedData$new(diamonds, key = ~cut, group = "color")

select_list <- crosstalk::filter_select(
    id = "test",
    label = "select list",
    sharedData = diamonds,
    group = ~cut,
    multiple = FALSE
  )

htmltools::browsable(htmltools::tagList(select_list,
                                        plot_ly(diamonds) |>
                                          add_trace(x =~cut, y =~x)))
```


```{r}

select_list <- crosstalk::filter_select(
    id = "test",
    label = "select list",
    sharedData = diamonds,
    group = ~cut,
    multiple = FALSE
  )

htmltools::browsable(htmltools::tagList(select_list,
                                        plot_ly(diamonds) |>
                                          add_trace(x =~cut, y =~y)))
```

**Comment by nanxstats** [comment]
@wangben718 Using different SharedData objects and different group identifiers solves it.

````rmd
---
output: html_document
---

```{r, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE)
```

```{r}
library(tidyverse)
library(crosstalk)
library(plotly)
```

```{r}
diamonds1 <- crosstalk::SharedData$new(diamonds, key = ~cut, group = "color1")
diamonds2 <- crosstalk::SharedData$new(diamonds, key = ~cut, group = "color2")

select_list1 <- crosstalk::filter_select(
  id = "id1",
  label = "select list",
  sharedData = diamonds1,
  group = ~cut,
  multiple = FALSE
)

htmltools::browsable(htmltools::tagList(
  select_list1,
  plot_ly(diamonds1) |> add_trace(x = ~cut, y = ~x)
))
```

```{r}
select_list2 <- crosstalk::filter_select(
  id = "id2",
  label = "select list",
  sharedData = diamonds2,
  group = ~cut,
  multiple = FALSE
)

htmltools::browsable(htmltools::tagList(
  select_list2,
  plot_ly(diamonds2) |> add_trace(x = ~cut, y = ~y)
))
```
````

**Comment by wangben718** [comment]
> @wangben718 Using different SharedData objects and different group identifiers solves it.
> 
> ```gfm
> ---
> output: html_document
> ---
> 
> ```{r, include=FALSE}
> knitr::opts_chunk$set(echo = FALSE, message = FALSE)
> ```
> 
> ```{r}
> library(tidyverse)
> library(crosstalk)
> library(plotly)
> ```
> 
> ```{r}
> diamonds1 <- crosstalk::SharedData$new(diamonds, key = ~cut, group = "color1")
> diamonds2 <- crosstalk::SharedData$new(diamonds, key = ~cut, group = "color2")
> 
> select_list1 <- crosstalk::filter_select(
>   id = "id1",
>   label = "select list",
>   sharedData = diamonds1,
>   group = ~cut,
>   multiple = FALSE
> )
> 
> htmltools::browsable(htmltools::tagList(
>   select_list1,
>   plot_ly(diamonds1) |> add_trace(x = ~cut, y = ~x)
> ))
> ```
> 
> ```{r}
> select_list2 <- crosstalk::filter_select(
>   id = "id2",
>   label = "select list",
>   sharedData = diamonds2,
>   group = ~cut,
>   multiple = FALSE
> )
> 
> htmltools::browsable(htmltools::tagList(
>   select_list2,
>   plot_ly(diamonds2) |> add_trace(x = ~cut, y = ~y)
> ))
> ```
> ```

Thanks for your demo!
